"""Generates reports/REPORT.md from the training results.

The report is written by the pipeline, never by hand, so the numbers in it can
never drift away from the numbers the model actually produced.
"""
from datetime import date
from pathlib import Path

import config

ROOT = Path(__file__).resolve().parent.parent


def _row(result: dict, name: str) -> dict:
    return next(r for r in result["rows"] if r["name"] == name)


def _fmt(value, spec: str = ".3f") -> str:
    return "—" if value is None else format(value, spec)


def _baseline_table(result: dict) -> str:
    head = ("| forecaster | Brier | BSS | PR-AUC | ROC-AUC | POD | FAR | CSI |\n"
            "|---|---|---|---|---|---|---|---|\n")
    body = ""
    for r in result["rows"]:
        body += (
            f"| {r['name']} | {r['brier']:.4f} | {_fmt(r['bss'], '+.3f')} | "
            f"{_fmt(r.get('pr_auc'))} | {_fmt(r.get('roc_auc'))} | "
            f"{_fmt(r['POD'])} | {_fmt(r['FAR'])} | {_fmt(r['CSI'])} |\n"
        )
    return head + body


def write(results: list[dict], ablation: dict | None = None) -> Path:
    first = results[0]
    raw = _row(first, "raw persistence (0/1)")
    calibrated = _row(first, "calibrated persistence")
    model = _row(first, "logistic regression")

    lines = [
        "# Next-day rain — verification report",
        "",
        "> Generated by `src/train.py`. Every number here comes out of the pipeline; none is",
        f"> typed by hand. Last run {date.today().isoformat()}.",
        "",
        "**Target:** precipitation tomorrow ≥ "
        f"{config.RAIN_THRESHOLD_MM} mm. The threshold separates a meaningful event from a",
        "trace, and was declared before anything was measured.",
        "",
        "---",
        "",
        "## The result that matters most",
        "",
        "Persistence — *\"tomorrow like today\"* — is the strongest single predictor there is.",
        f"Expressed as a hard yes/no it scores a Brier of {raw['brier']:.4f}, a skill score of",
        f"**{raw['bss']:+.3f}: worse than saying nothing at all.** The same information, expressed",
        f"as a calibrated probability, scores {calibrated['bss']:+.3f}.",
        "",
        f"That is {abs(calibrated['bss'] - raw['bss']):.2f} of Brier Skill Score **from the same",
        "signal**, moved entirely by calibration. Having the right predictor is not enough; it has",
        f"to be expressed as a probability. ({first['location'].name}; the pattern holds at all",
        "five locations.)",
        "",
        "---",
        "",
        "## Protocol",
        "",
        "| location | train | validation | test | train base rate | test base rate |",
        "|---|---|---|---|---|---|",
    ]
    for r in results:
        w, s, b = r["windows"], r["sizes"], r["base_rates"]
        lines.append(
            f"| {r['location'].name} | {w['train'][0]} → {w['train'][1]} ({s['train']}) | "
            f"{w['validation'][0][:7]} ({s['validation']}) | "
            f"{w['test'][0]} → {w['test'][1]} ({s['test']}) | "
            f"{b['train']:.3f} | {b['test']:.3f} |"
        )

    lines += [
        "",
        "The split is **temporal, never random**: a day from 2023 cannot land in the test set",
        "alongside its neighbour from 2024. The test period lies entirely *after* the end of",
        "training, and is the same stretch of time the live daily forecasts run in.",
        "",
        "Regularisation was chosen on the validation year alone. The test set was scored once.",
        "",
        "---",
        "",
        "## Stop criterion",
        "",
        "Fixed in writing before any result was seen:",
        "",
        f"> the model must beat **calibrated persistence** by at least",
        f"> **{0.05:.2f}** of Brier Skill Score on the held-out test set.",
        "",
        "Relative, not absolute, and deliberately so. Calibrated persistence is a three-line Markov",
        "chain that already scores well; beating climatology would prove nothing.",
        "",
        "| location | model BSS | persistence BSS | gain | verdict |",
        "|---|---|---|---|---|",
    ]
    for r in results:
        m, p = _row(r, "logistic regression"), _row(r, "calibrated persistence")
        lines.append(
            f"| {r['location'].name} | {m['bss']:+.3f} | {p['bss']:+.3f} | "
            f"**{r['gain']:+.3f}** | {'PASS' if r['passed'] else '**FAIL**'} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Skill across the rainfall gradient",
        "",
        "The five locations were not chosen at random: they span a real gradient from the",
        "Prealpine foothills to the lagoon, inside about 80 km.",
        "",
        "| location | mm/yr (test) | test base rate | Brier | BSS | ROC-AUC | reliability | resolution |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        m = _row(r, "logistic regression")
        d = r["decomposition"]
        lines.append(
            f"| {r['location'].name} | — | {r['base_rates']['test']:.3f} | {m['brier']:.4f} | "
            f"{m['bss']:+.3f} | {_fmt(m.get('roc_auc'))} | {d['reliability']:.4f} | "
            f"{d['resolution']:.4f} |"
        )

    lines += [
        "",
        "Brier decomposes as **reliability − resolution + uncertainty**. Low reliability is good",
        "(the probabilities mean what they say); high resolution is good (rainy days are separated",
        "from dry ones). Reporting only the total hides which of the two is driving a difference.",
        "",
        "---",
        "",
        "## What the model learned",
        "",
        "Standardised coefficients, so they are comparable with each other and across locations.",
        "No physical rule was imposed — this is least squares on a sigmoid.",
        "",
        "| feature | " + " | ".join(r["location"].name.split()[0] for r in results) + " | meaning |",
        "|---|" + "---|" * (len(results) + 1),
    ]
    from train import FEATURE_GLOSS, FEATURES  # local import: avoids a cycle at module load

    order = sorted(FEATURES, key=lambda f: -abs(results[0]["coefficients"][f]))
    for feature in order:
        values = " | ".join(f"{r['coefficients'][feature]:+.3f}" for r in results)
        lines.append(f"| `{feature}` | {values} | {FEATURE_GLOSS[feature]} |")

    lines += [
        "",
        "---",
        "",
        "## Reliability",
        "",
        f"When the model says 70%, does it rain 70% of the time? ({first['location'].name})",
        "",
        "| predicted | observed | n |",
        "|---|---|---|",
    ]
    for b in first["reliability"]:
        lines.append(f"| {b['predicted']:.2f} | {b['observed']:.2f} | {b['n']} |")

    lines += [
        "",
        "---",
        "",
        "## The decision threshold",
        "",
        "Not a technical detail: it governs what anyone acting on the forecast actually does.",
        f"({first['location'].name})",
        "",
        "| threshold | POD | FAR | CSI | warnings issued |",
        "|---|---|---|---|---|",
    ]
    for t in first["threshold_sweep"]:
        lines.append(
            f"| {t['threshold']:.1f} | {_fmt(t['POD'])} | {_fmt(t['FAR'])} | "
            f"{_fmt(t['CSI'])} | {t['n_warnings']} of {t['n']} |"
        )

    lines += [
        "",
        "The default of 0.5 is rarely the right operating point. Where the costly error is a",
        "*missed* event — a fungicide applied and then washed off — the threshold belongs lower,",
        "and the CSI-maximising value is the place to start.",
        "",
    ]

    if ablation:
        s, l = ablation["short_window"], ablation["long_window"]
        better = "the long window" if ablation["difference"] > 0 else "the short window"
        lines += [
            "---",
            "",
            "## Does the uniform training window cost anything?",
            "",
            "The 2016 start is necessary in the foothills, where the rainfall regime shifted, and",
            "unnecessary over the plain, where it did not (see `METHOD_NOTES.md` §2). Applying it",
            "everywhere discards roughly two thirds of the history at the stable sites. Whether",
            f"that costs measurable skill is a question the data can answer, so — {ablation['location']},",
            "trained both ways, scored on the same held-out test set:",
            "",
            "| training window | day pairs | BSS |",
            "|---|---|---|",
            f"| from {s['start']} | {s['n']} | {s['bss']:+.4f} |",
            f"| from {l['start']} | {l['n']} | {l['bss']:+.4f} |",
            "",
            f"Difference: **{ablation['difference']:+.4f}** in favour of {better}.",
            "",
        ]

    lines += [
        "---",
        "",
        "## Declared limits",
        "",
        "- **A single grid point per location**, not a spatial field. At the scale of one town that",
        "  is a choice, not an oversight — spatial downscaling would be wasted work here.",
        "- **Autocorrelation.** Consecutive days are far from independent, so the effective sample",
        "  size is much smaller than the row count and confidence intervals are wider than the",
        "  number of rows suggests.",
        "- **Cause of the non-stationarity.** With one reanalysis and three decades, a real climate",
        "  signal cannot be fully separated from an inhomogeneity in how ERA5 represents a",
        "  particular cell. The operational consequence is the same either way, so the decision",
        "  does not rest on separating them.",
        "- **Reanalysis versus real time.** The model is trained on ERA5 and served from ERA5, which",
        "  removes the product skew — but the most recent days of the archive are preliminary, and",
        "  that residual difference is not quantified here.",
        "",
    ]

    out = ROOT / "reports" / "REPORT.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
